GET http://localhost:3000/v1/api/olimpic/results/list?offset=1&limit=10
Content-Type: application/json

###

POST http://localhost:3000/v1/api/olimpic/results/add
Content-Type: application/json

{
  "country": "poland",
  "image": "https://example.ex/img",
  "medalsOverall": 1,
  "medals": {
    "gold": 0,
    "silver": 1,
    "bronze": 0
  }
}

###

DELETE  http://localhost:3000/v1/api/olimpic/results/remove/2
Content-Type: application/json

###

POST http://localhost:3000/v1/api/olimpic/results/add
Content-Type: application/json

{
  "country1": "poland",
  "image": "https://example.ex/img",
  "medalsOverall": 1,
  "medals": {
    "gold": 0,
    "silver": 1,
    "bronze": 0
  }
}
